name: Process Telegram Updates

on:
  repository_dispatch:
    types: [telegram-update]

jobs:
  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Add Update
        run: |
          # Create updates directory if it doesn't exist
          mkdir -p updates
          
          # Create the update file with timestamp as name
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "${{ github.event.client_payload.content }}" > "updates/${TIMESTAMP}.txt"
          
          # Update index.html with the new content
          python - <<EOF
          import os
          import glob
          from datetime import datetime
          import re
          
          def get_latest_updates():
              # Get all update files sorted by timestamp (newest first)
              update_files = sorted(glob.glob('updates/*.txt'), reverse=True)
              
              # Get content and dates for the 3 most recent updates
              updates = []
              for file in update_files[:3]:  # Only take the 3 most recent updates
                  with open(file, 'r', encoding='utf-8') as f:
                      content = f.read().strip()
                  # Get date from filename (YYYYmmdd_HHMMSS)
                  timestamp = os.path.basename(file).replace('.txt', '')
                  date = datetime.strptime(timestamp, '%Y%m%d_%H%M%S')
                  date_str = date.strftime('%Y-%m-%d %H:%M')
                  updates.append({
                      'content': content,
                      'date': date_str
                  })
              return updates

          def update_index_html():
              with open('index.html', 'r', encoding='utf-8') as f:
                  content = f.read()

              # Get the latest updates
              updates = get_latest_updates()

              # Create the new updates HTML
              updates_html = ''
              for update in updates:
                  updates_html += f'''
                  <div class="update-item mb-4">
                      <div class="card">
                          <div class="card-body">
                              <p class="card-text">{update['content']}</p>
                              <p class="card-text"><small class="text-muted">Posted on {update['date']}</small></p>
                          </div>
                      </div>
                  </div>'''

              # Find the updates section and replace its content
              pattern = r'(<div class="updates-list">).*?(</div>\s*<!-- Initial welcome message -->)'
              replacement = r'\1' + updates_html + r'\2'
              new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

              # Write the updated content back to index.html
              with open('index.html', 'w', encoding='utf-8') as f:
                  f.write(new_content)

          update_index_html()
          EOF

          # Stage and commit the changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add index.html updates/
          git commit -m "Update website with new Telegram message"
          git push origin main
          
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NoCoMozi/MayDayMovement-clean/pages/builds
