name: Process Telegram Updates

on:
  repository_dispatch:
    types: [telegram-update]

jobs:
  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install BeautifulSoup
        run: pip install beautifulsoup4
          
      - name: Add Update
        run: |
          # Create updates directory if it doesn't exist
          mkdir -p updates
          
          # Create the update file with timestamp as name
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "${{ github.event.client_payload.content }}" > "updates/${TIMESTAMP}.txt"
          
          # Update index.html with the new content
          python - <<EOF
          import os
          from datetime import datetime
          from bs4 import BeautifulSoup
          
          def add_update_to_html():
              with open('index.html', 'r', encoding='utf-8') as f:
                  content = f.read()
              
              # Parse the HTML content
              soup = BeautifulSoup(content, 'html.parser')
              
              # Find the updates-list div
              updates_list = soup.find('div', class_='updates-list')
              if not updates_list:
                  print("Could not find updates-list div")
                  return
              
              # Create the new update element
              new_update = soup.new_tag('div', attrs={'class': 'update-item mb-4'})
              card = soup.new_tag('div', attrs={'class': 'card'})
              card_body = soup.new_tag('div', attrs={'class': 'card-body'})
              
              # Add the content
              content_p = soup.new_tag('p', attrs={'class': 'card-text'})
              content_p.string = "${{ github.event.client_payload.content }}"
              
              date_p = soup.new_tag('p', attrs={'class': 'card-text'})
              date_small = soup.new_tag('small', attrs={'class': 'text-muted'})
              date_small.string = f"Posted on ${{ github.event.client_payload.date }}"
              date_p.append(date_small)
              
              card_body.append(content_p)
              card_body.append(date_p)
              card.append(card_body)
              new_update.append(card)
              
              # Insert the new update at the beginning
              updates_list.insert(0, new_update)
              
              # Keep only the 3 most recent updates
              update_items = updates_list.find_all('div', class_='update-item', recursive=False)
              for item in update_items[3:]:
                  item.decompose()
              
              # Write the updated content back to the file
              with open('index.html', 'w', encoding='utf-8') as f:
                  f.write(str(soup.prettify()))
              
              print("Successfully added new update to index.html")
          
          add_update_to_html()
          EOF
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add updates/ index.html
          git commit -m "Add update from Telegram: ${{ github.event.client_payload.content }}"
          git push
