name: Process Telegram Updates

on:
  repository_dispatch:
    types: [telegram-update]

jobs:
  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Add Update
        run: |
          # Create updates directory if it doesn't exist
          mkdir -p updates
          
          # Create the update file with timestamp as name
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "${{ github.event.client_payload.content }}" > "updates/${TIMESTAMP}.txt"
          
          # Update index.html with the new content
          python - <<EOF
          import os
          from datetime import datetime
          import re
          
          def add_update_to_html():
              with open('index.html', 'r', encoding='utf-8') as f:
                  content = f.read()
              
              # Find the updates-list div
              updates_list_start = content.find('<div class="updates-list">')
              if updates_list_start == -1:
                  print("Could not find updates-list div")
                  return
              
              # Find the end of the opening div tag
              insert_point = content.find('>', updates_list_start) + 1
              
              # Create the new update HTML
              new_update = f"""
                <div class="update-item mb-4">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{os.environ.get('GITHUB_EVENT_CONTENT', "${{ github.event.client_payload.content }}")}</p>
                            <p class="card-text"><small class="text-muted">Posted on {os.environ.get('GITHUB_EVENT_DATE', "${{ github.event.client_payload.date }}")}</small></p>
                        </div>
                    </div>
                </div>"""
              
              # Get all existing updates
              updates_section = content[updates_list_start:]
              end_updates = updates_section.find('</div>') + len('</div>')
              updates_html = updates_section[:end_updates]
              
              # Find all update items
              update_items = re.findall(r'<div class="update-item mb-4">.*?</div>\s*</div>\s*</div>', updates_html, re.DOTALL)
              
              # Keep only the 2 most recent updates (we'll add the new one to make 3)
              kept_updates = update_items[:2] if update_items else []
              
              # Create new content with limited updates
              new_content = content[:insert_point] + new_update
              for update in kept_updates:
                  new_content += update
              new_content += content[updates_list_start + end_updates:]
              
              # Write the updated content back to the file
              with open('index.html', 'w', encoding='utf-8') as f:
                  f.write(new_content)
              
              print("Successfully added new update to index.html")
          
          add_update_to_html()
          EOF
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add updates/ index.html
          git commit -m "Add update from Telegram: ${{ github.event.client_payload.content }}"
          git push
